networks:
  url-shortener:
    name: url-shortener
    driver: bridge

services:

  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    hostname: url-shortener
    networks:
      - url-shortener
    ports:
      - "8080:8080"
    restart: unless-stopped
